# Generated by Django 6.0.5 on 2026-05-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('truck_number', models.CharField(blank=True, max_length=50)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_city', models.CharField(max_length=120)),
                ('to_city', models.CharField(max_length=120)),
                ('cargo_type', models.CharField(blank=True, max_length=120)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('client_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('driver_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank transfer')], default='cash', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.load')),
            ],
        ),
    ]
