# Generated by Django 6.0.5 on 2026-05-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='announcement_chat_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='load',
            name='announcement_message_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='cargo_volume',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='load',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='load',
            name='from_region',
            field=models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('sirdaryo', 'Sirdaryo'), ('jizzax', 'Jizzax'), ('samarqand', 'Samarqand'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', "Qoraqalpog'iston")], max_length=40),
        ),
        migrations.AddField(
            model_name='load',
            name='logist_contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='load',
            name='owner_contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='load',
            name='price_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='load',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Summa belgilangan'), ('negotiable', 'Kelishiladi')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='to_region',
            field=models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('sirdaryo', 'Sirdaryo'), ('jizzax', 'Jizzax'), ('samarqand', 'Samarqand'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', "Qoraqalpog'iston")], max_length=40),
        ),
        migrations.AddField(
            model_name='load',
            name='weight_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('cargo_owner', 'Yuk egasi'), ('driver', 'Haydovchi'), ('logist', 'Logist')], max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('truck_number', models.CharField(blank=True, max_length=50)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('sirdaryo', 'Sirdaryo'), ('jizzax', 'Jizzax'), ('samarqand', 'Samarqand'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', "Qoraqalpog'iston")], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='assigned_driver_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_loads', to='logistics.telegramprofile'),
        ),
        migrations.AddField(
            model_name='load',
            name='created_by_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loads', to='logistics.telegramprofile'),
        ),
    ]
