# Generated by Django 6.0.5 on 2026-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_load_announcement_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
